// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxa_kJTu7C5MXwRc4Z438DhLCtRzAVaF4',
    appId: '1:347552137752:web:7348034b61744f4add796d',
    messagingSenderId: '347552137752',
    projectId: 'geo-flutter-fire',
    authDomain: 'geo-flutter-fire.firebaseapp.com',
    storageBucket: 'geo-flutter-fire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmd4lPyoulwedDWro7e6j1oP4jVGJKbSI',
    appId: '1:347552137752:android:42b7cec050988560dd796d',
    messagingSenderId: '347552137752',
    projectId: 'geo-flutter-fire',
    storageBucket: 'geo-flutter-fire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOtvwU03LZ-c0FwwkwG12ItjN5IHEhYp4',
    appId: '1:347552137752:ios:95fe166e7f8422d9dd796d',
    messagingSenderId: '347552137752',
    projectId: 'geo-flutter-fire',
    storageBucket: 'geo-flutter-fire.appspot.com',
    iosClientId: '347552137752-3d10v9s9n4121vgoordp84oubsk8vbrr.apps.googleusercontent.com',
    iosBundleId: 'com.mezops.geo.flutter.fire',
  );
}
